# Generated by Django 5.0.4 on 2024-05-16 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockassets',
            old_name='stock_amount',
            new_name='stock_value_amount',
        ),
        migrations.AddField(
            model_name='buystockhistory',
            name='stock_purchased_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AddField(
            model_name='buystockhistory',
            name='ticker',
            field=models.CharField(default='----', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashassets',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AlterField(
            model_name='stockassets',
            name='stock_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AlterField(
            model_name='stockassets',
            name='ticker',
            field=models.CharField(default='----', max_length=10),
        ),
        migrations.CreateModel(
            name='SellStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField(auto_now_add=True)),
                ('stock_sold_amount', models.DecimalField(decimal_places=2, default=0, max_digits=99)),
                ('ticker', models.CharField(default='----', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
