# Generated by Django 5.0.4 on 2024-05-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_rename_stock_amount_stockassets_stock_value_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buystockhistory',
            old_name='stock_purchased_amount',
            new_name='stock_purchased_count',
        ),
        migrations.AddField(
            model_name='buystockhistory',
            name='stock_value_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999),
        ),
        migrations.AddField(
            model_name='sellstockhistory',
            name='stock_value_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999),
        ),
    ]
