# Generated by Django 5.0.4 on 2024-05-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_rename_stock_purchased_amount_buystockhistory_stock_purchased_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellstockhistory',
            old_name='stock_sold_amount',
            new_name='stock_sold_count',
        ),
    ]
