# Generated by Django 5.0.4 on 2024-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_rename_stock_sold_amount_sellstockhistory_stock_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashassets',
            name='total_cash_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
    ]
